services:
  db:
    image: 'bitnami/postgresql:latest'
    ports:
      - '5432:5432'
    restart: always
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=upload_db
    volumes:
      - './docker:/docker-entrypoint-initdb.d'
